### ISSUE TITLE
macos终端跑优选ip脚本，提示./cfcdnip: cannot execute binary file

### ISSUE THREAD

**Issue by Mrycp** [yonggekkk/Cloudflare-workers-pages-vless#11]
macos终端跑优选ip脚本有如下两个问题：
1.提示ip.csv文件不存在
2.修改ip.txt文件为csv文件后继续报错
3.报错提示： ./cfcdnip: cannot execute binary file

**Comment by yonggekkk** [comment]
默认就提供了AMD64、386、ARM64。。。三种，不知MACOS是另外哪种
