### ISSUE TITLE
IOS下CF优选IP代码报错

### ISSUE THREAD

**Issue by quan9364** [yonggekkk/Cloudflare-workers-pages-vless#12]
如图，ios下载了ish并更新依赖后，执行优选IP脚本仍然报错，请yg看看如何解决，谢谢

![fde084d900080c2ab5b6429e7467be2](https://github.com/yonggekkk/Cloudflare-workers-pages-vless/assets/104670680/79bb71bb-0bbc-4a0d-baa6-43b3fa202f8a)

**Comment by yonggekkk** [comment]
先挂代理试一次下载必要文件！再重试

**Comment by quan9364** [comment]
可以了，多谢ygOn Aug 24, 2023, at 22:20, 甬哥侃侃侃ygkkk ***@***.***> wrote:﻿
先挂代理试一次下载必要文件！再重试

**Comment by C018** [comment]
这个要啊能指定地区优选就好了，比如台湾澳门马来西亚什么的

**Comment by wuya110** [comment]
![IMG_1707](https://github.com/yonggekkk/Cloudflare-workers-pages-vless/assets/147088502/c74ccba7-9008-494c-b838-816c8f7a4ab2)
我的就这么卡着

**Comment by yonggekkk** [comment]
> ![IMG_1707](https://private-user-images.githubusercontent.com/147088502/293510838-c74ccba7-9008-494c-b838-816c8f7a4ab2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwNTEwNTIsIm5iZiI6MTcwNDA1MDc1MiwicGF0aCI6Ii8xNDcwODg1MDIvMjkzNTEwODM4LWM3NGNjYmE3LTkwMDgtNDk0Yy1iODM4LTgxNmM4ZjdhNGFiMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIzMVQxOTI1NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MTE4YWZlZmE1MWJmN2E5NzBjNWVmMGM3NWEzMWEyZjFmMDMxOWRmYmIzNzZhNmY5ZDgxODNlMTU2YWI5Nzg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mLFdS3wmJ8jVNHoIgLmAQ5O1bU2m_797gDD1ej5m-7I) 我的就这么卡着

苹果的ish有bug，正常！要多次运行
