### ISSUE TITLE
ip.csv 找不到

### ISSUE THREAD

**Issue by DeepSeaCat** [yonggekkk/Cloudflare-workers-pages-vless#18]
<img width="570" alt="image" src="https://github.com/yonggekkk/Cloudflare-workers-pages-vless/assets/59075180/ff676d70-24a0-4c41-a464-d6881075b6e2">

**Comment by DeepSeaCat** [comment]
可能是由于没有有效ip，就没有生成相关的ip.csv

**Comment by yonggekkk** [comment]
苹果电脑有兼容问题

**Comment by Giancarlo-Ma** [comment]
linux一样的错误
