### ISSUE TITLE
请教如何找到澳洲的proxyIP~

### ISSUE THREAD

**Issue by alexallen1** [yonggekkk/Cloudflare-workers-pages-vless#20]
感谢楼主做出如此好的脚本
关于proxyIP默认为香港地区，
请教如何换成可用的澳洲ip，学术访问用
不方便公布的话请https://t.me/goldn133 ~我只是个人用用。感谢

**Comment by yonggekkk** [comment]
这个你要自己找反代ip了！一般proxyip主要是访问cf用

**Comment by redstoneleo** [comment]
这里有方法，但我没有试过，您可以试试看，能用的话说一声
https://blog.tanglu.me/cloudflare_proxy_ip/
