### ISSUE TITLE
clash如何使用

### ISSUE THREAD

**Issue by codeMauguin** [yonggekkk/Cloudflare-workers-pages-vless#21]
想请教下这个clash如何导入这个节点呢

**Comment by yonggekkk** [comment]
[Clash零基础终极教程：告别节点泄露被盗！无须订阅转换！全网首发自建Clash模版订阅链接，手搓代理协议设置，软路由openclash、电脑clash-verge、苹果小火箭、clash-meta](https://youtu.be/LYeLN9esgaw)

**Comment by codeMauguin** [comment]
谢谢🙏发自我的 iPhone在 2023年10月18日，13:05，甬哥侃侃侃ygkkk ***@***.***> 写道：﻿
Clash零基础终极教程：告别节点泄露被盗！无须订阅转换！全网首发自建Clash模版订阅链接，手搓代理协议设置，软路由openclash、电脑clash-verge、苹果小火箭、clash-meta
