### ISSUE TITLE
sing_box优选ip不显示?

### ISSUE THREAD

**Issue by RzdPai** [yonggekkk/Cloudflare-workers-pages-vless#214]
![Screenshot_2024-12-14-00-16-22-08_a252b927494330cdc2c8ba3b3f952e5e.jpg](https://github.com/user-attachments/assets/88793316-aa02-4bbf-a57f-ac5e54adb441)
![Screenshot_2024-12-14-00-13-59-95_d2ee0e1115b0a64ebff5994ebce8502f.jpg](https://github.com/user-attachments/assets/14cfa61f-2c39-4ab3-b65a-3cc61f6af79f)

**Comment by RzdPai** [comment]
> Pages？变量设后要重新上传资产，见最新视频教程

Worker

**Comment by yonggekkk** [comment]
更新同步下订阅连接

**Comment by RzdPai** [comment]
> 更新同步下订阅连接

更新了，没用，而且通用订阅用不了，只能用sing_box订阅节点，是不是《以下订阅链接仅6个TLS端口节点》的问题

**Comment by yonggekkk** [comment]
变量值书写是否有问题

**Comment by RzdPai** [comment]
> 变量值书写是否有问题

检查了，没有空格和回车

**Comment by RzdPai** [comment]
> 变量值书写是否有问题

检查了，没有空格和回车

**Comment by yonggekkk** [comment]
重新建个吧
