### ISSUE TITLE
很多网站显示证书无效打不开

### ISSUE THREAD

**Issue by zzzb1024** [yonggekkk/Cloudflare-workers-pages-vless#22]
workers-vless代理，好像从两周前开始，Cloudflare，speedtest，Deepl，gitlab，openwrt.ai，等等....好多网站都打不开（大部分都是显示不安全证书无效打不开），不管用什么优选IP，域名，只能打开google，youtube之类的。以前都不是这样的，是怎么回事啊？

**Comment by yonggekkk** [comment]
Proxyip改为脚本默认ip

**Comment by zzzb1024** [comment]
> Proxyip改为脚本默认ip

确实换回默认ip解决问题了，谢谢涌哥

**Comment by KingkissQueen** [comment]
target UUID=???????.....，从何而来，可以更换吗
