### ISSUE TITLE
很多网站都打不开主要是亚洲网站

### ISSUE THREAD

**Issue by yongkangz428** [yonggekkk/Cloudflare-workers-pages-vless#26]
甬哥代码我没做改动就那样部署上去的不仅是亚洲网站无法访问，用代理工具测速的时候显示超时，我也不知道怎么回事

**Comment by yonggekkk** [comment]
proxyip改动了吗？

**Comment by yongkangz428** [comment]
@yonggekkk 没有

**Comment by yonggekkk** [comment]
哪些网站？

**Comment by yonggekkk** [comment]
应该是proxyip用的人太多，CF类网站访问慢。。。

**Comment by yongkangz428** [comment]
@yonggekkk 那该怎么解决这问题？
进不去的网站https://www.pixiv.net/?lang=zh
https://hanime1.me/watch?v=12231
https://www.iwara.tv

**Comment by yonggekkk** [comment]
> @yonggekkk 那该怎么解决这问题？ 进不去的网站https://www.pixiv.net/?lang=zh https://hanime1.me/watch?v=12231 https://www.iwara.tv

果然都是CF类网站，换proxyIP吧。。

**Comment by yongkangz428** [comment]
@yonggekkk 知道了，谢谢
