### ISSUE TITLE
甬哥可以出个自建proxyIP的教程吗？

### ISSUE THREAD

**Issue by PeterHgg** [yonggekkk/Cloudflare-workers-pages-vless#27]
RT，想用德鸡解锁部分网站，如GPT

**Comment by yonggekkk** [comment]
这方面除了市面流行的，我并不了解太多。。哈哈

**Comment by redstoneleo** [comment]
https://blog.tanglu.me/cloudflare_proxy_ip/
这里有方法，但我没有试过，您可以试试看，能用的话说一声
