### ISSUE TITLE
优选脚本报错

### ISSUE THREAD

**Issue by creeperCN** [yonggekkk/Cloudflare-workers-pages-vless#31]
~ $ curl -sSL https://gitlab.com/rwkgyg/CFwarp/raw/main/point/cfip.sh -o cfip.sh && chmod +x cfip.sh && bash cfip.sh
------------------------------------------------------
甬哥Github项目  ：github.com/yonggekkk
甬哥blogger博客 ：ygkkk.blogspot.com
甬哥YouTube频道 ：www.youtube.com/@ygkkk
------------------------------------------------------
筛选ProxyIP + CF反代IP脚本，IP库来源于热心网友
------------------------------------------------------

1.就近自动优选CF反代IP
2.重置并清理已下载文件
0.退出
请选择: 1
##################################### 100.0%
curl: (35) Recv failure: Connection reset by peer

开启tls的端口：443、8443、2053、2083、2087、2096
关闭tls的端口：80、8080、8880、2052、2082、2086、2095
请选择以上13个端口之一：443
find: ‘txt’: No such file or directory
是否测速？（选择 1 测速，回车默认不测速）
请选择: 1
# XIU2/CloudflareSpeedTest v2.2.4

[信息] 延迟测速结果 IP 数量为 0，跳过下载测 速。

[信息] 完整测速结果 IP 数量为 0，跳过输出结 果。

稍等1分钟，对优选反代IP进行地区识别，并做排 名
awk: fatal: cannot open file `result.csv' for reading: No such file or directory
grep: b.csv: No such file or directory
grep: b.csv: No such file or directory
grep: b.csv: No such file or directory
grep: b.csv: No such file or directory
grep: b.csv: No such file or directory
grep: b.csv: No such file or directory
grep: b.csv: No such file or directory
grep: b.csv: No such file or directory
grep: b.csv: No such file or directory
grep: b.csv: No such file or directory

根据每个地区，排名前三的优选IP如下：
~ $

**Comment by yonggekkk** [comment]
升级curl，或用官方ip

**Comment by creeperCN** [comment]
如何解决？

**Comment by yonggekkk** [comment]
> 如何解决？

curl依赖升级了吗？先挂代理下载，看看curl会不会报错。

**Comment by xinzhongyouhai** [comment]
WINDOWS上用的脚本也出错了~用不了咯~

**Comment by yonggekkk** [comment]
> WINDOWS上用的脚本也出错了~用不了咯~

一般都网络问题。。发下什么报错信息

**Comment by xinzhongyouhai** [comment]
![image](https://github.com/yonggekkk/Cloudflare-workers-pages-vless/assets/128223360/bf230de8-7eec-466c-973f-72742d1de33d)

**Comment by xinzhongyouhai** [comment]
![image](https://github.com/yonggekkk/Cloudflare-workers-pages-vless/assets/128223360/ece93547-9794-4090-9a58-a52484afc8d6)
