### ISSUE TITLE
优选域名exe WIN11 报错

### ISSUE THREAD

**Issue by zionttsang** [yonggekkk/Cloudflare-workers-pages-vless#33]
![QQ截图20231126163924](https://github.com/yonggekkk/Cloudflare-workers-pages-vless/assets/18133809/e04f09dd-d81b-4401-acf7-25efd42217cf)

**Comment by yonggekkk** [comment]
基于win10的，可能是不支持W11，，后面我更新下

**Comment by zionttsang** [comment]
> 基于win10的，可能是不支持W11，，后面我更新下

辛苦涌哥~~

**Comment by yonggekkk** [comment]
> > 基于win10的，可能是不支持W11，，后面我更新下
> 
> 辛苦涌哥~~

先试试右击属性-兼容性-兼容模式改下

**Comment by zionttsang** [comment]
> > > 基于win10的，可能是不支持W11，，后面我更新下
> > 
> > 
> > 辛苦涌哥~~
> 
> 先试试右击属性-兼容性-兼容模式改下

这个第一时间就试过了，兼容性选WIN7或者WIN8都不行。
