### ISSUE TITLE
MacOS 优选反代IP 脚本执行报错

### ISSUE THREAD

**Issue by mengchy** [yonggekkk/Cloudflare-workers-pages-vless#36]
MacOS 执行这个脚本报错，如图
![image](https://github.com/yonggekkk/Cloudflare-workers-pages-vless/assets/19759159/97f20ba5-ab4d-44d3-b8d6-5e830dd8ca28)

**Comment by yonggekkk** [comment]
mac我没测试，可能是有兼容问题。。
