### ISSUE TITLE
我的ish不行

### ISSUE THREAD

**Issue by rrn21833** [yonggekkk/Cloudflare-workers-pages-vless#38]
![E0C1BFB4-0691-451E-8895-1CF650BA4985](https://github.com/yonggekkk/Cloudflare-workers-pages-vless/assets/37966911/bc417c5a-d2f7-4f9a-b0e6-dbd0710400ec)

**Comment by yonggekkk** [comment]
> ![E0C1BFB4-0691-451E-8895-1CF650BA4985](https://private-user-images.githubusercontent.com/37966911/292699327-bc417c5a-d2f7-4f9a-b0e6-dbd0710400ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NzE2NTcsIm5iZiI6MTcwMzQ3MTM1NywicGF0aCI6Ii8zNzk2NjkxMS8yOTI2OTkzMjctYmM0MTdjNWEtZDJmNy00ZjlhLWIwZTYtZGJkMDcxMDQwMGVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDAyMjkxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzNjkyMzJmNWJlNTA5YTg2NTE4NGE1NmNhMjcwNWQzZjQzMzgwNDE0MGNkNzBkNDAwZTE5ZDFmZjY4OGY3OGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YujnJ8AX6y8wNujuJqSZ2O-bFXSu-ZYnheG25RmECBs)

换个代理来更新试试

**Comment by rrn21833** [comment]
代理能正常运行；本地网络不行？可能gitlab被墙了（问：每次启动ish需要粘贴依赖代码吗？谢谢）
![CC761FE4-74FB-4579-B69F-4019DF35A8BD](https://github.com/yonggekkk/Cloudflare-workers-pages-vless/assets/37966911/9f179a9f-1288-4452-b83c-1ca82a51f597)
![0837FCDB-413E-4D44-BF51-3027998FC2A6](https://github.com/yonggekkk/Cloudflare-workers-pages-vless/assets/37966911/2b005887-4e3c-40c7-ba46-0987a5b4ab9d)

**Comment by yonggekkk** [comment]
一次装好就行了。。你卸载重装下

**Comment by rrn21833** [comment]
卸载重装后一样的。开代理可以，本地还是不行（问：排序结果可用于proxyIPs吗？谢谢）
![2B12D824-A10D-495E-B2EB-AD681D9FB619](https://github.com/yonggekkk/Cloudflare-workers-pages-vless/assets/37966911/12996ca7-b524-4a32-a6e2-0dbabcba62cc)
![0BD3E33E-C2D5-4D52-867A-E413F80E4AB1](https://github.com/yonggekkk/Cloudflare-workers-pages-vless/assets/37966911/fc85c785-3e19-4643-8a81-e55ccae66abb)
![8A2ECDBF-D7EB-48CF-B24C-50B94B1FC89E](https://github.com/yonggekkk/Cloudflare-workers-pages-vless/assets/37966911/82d4bde0-21f8-4487-8dbf-1e8b30c7dbd9)

**Comment by yonggekkk** [comment]
proxyIP不一定能用，域名是直接用在客户端地址上的

**Comment by rrn21833** [comment]
喜讯：手动改手机系统DNS后（原自动）现在可以本地运行了。谢谢甬哥。
![CFB4B937-98F5-4878-9BBC-ED4FEE9CAC58](https://github.com/yonggekkk/Cloudflare-workers-pages-vless/assets/37966911/97d1f720-b335-48f7-be1c-4b710923818a)

**Comment by yonggekkk** [comment]
还真是DNS问题是大头。。。。。
