### ISSUE TITLE
是否有计划对接 v2board 上报流量/限速等其它 API

### ISSUE THREAD

**Issue by lslzl3000** [yonggekkk/Cloudflare-workers-pages-vless#39]
我看脚本里有通过 v2board api 拿 user uuid，但好像没有对接其他api了，是否有计划对接呢？
如果第三方提交pr对接 v2board 可以吗？
如果做的话，大概在脚本哪个部分做这个功能合适？

**Comment by yonggekkk** [comment]
这个不会支持
