### ISSUE TITLE
IOS ISH反代IP会扫一会儿会停止

### ISSUE THREAD

**Issue by lnjamn** [yonggekkk/Cloudflare-workers-pages-vless#44]
IOS ISH反代IP会扫一会儿会停止?![image](https://github.com/yonggekkk/Cloudflare-workers-pages-vless/assets/18238323/0b2c5d27-c477-42ca-aa1a-fdb840be4e77)

**Comment by lnjamn** [comment]
![image](https://github.com/yonggekkk/Cloudflare-workers-pages-vless/assets/18238323/55cc601d-fe72-4c02-a7f2-89f8469aaae3)

**Comment by yonggekkk** [comment]
ISH是有这个问题。。目前只能这样反复多次凑合用了
