### ISSUE TITLE
勇哥,你把我踢出群的目的原来是为了把我的ProxyIP扒来下自己发吗?

### ISSUE THREAD

**Issue by cmliu** [yonggekkk/Cloudflare-workers-pages-vless#46]
勇哥,你把我踢出群的目的原来是为了把我的ProxyIP扒来下自己发吗?

**Comment by yonggekkk** [comment]
> 勇哥,你把我踢出群的目的原来是为了把我的ProxyIP扒来下自己发吗?

把你t了？不好意思！广告太多误t了！己解，欢迎回来！再次向你道歉！！
