### ISSUE TITLE
优选出的反代ip有速度，但vless不能连接套cf的网站

### ISSUE THREAD

**Issue by rainpoi** [yonggekkk/Cloudflare-workers-pages-vless#49]
筛选的速度和延迟都还行，但是放入ProxyIP重新部署后（连端口都按要求改写过），访问youtube正常，不能访问套cf的网站。
请问是优选的方式有问题，还是使用上有什么注意的点？

**Comment by yonggekkk** [comment]
Proxyip与反代ip不相等！不能混用！Proxyip用默认的戓分享的就行

**Comment by rainpoi** [comment]
> Proxyip与反代ip不相等！不能混用！Proxyip用默认的戓分享的就行

感谢回复，
因为看了很多视频，把反代ip填在proxyip，可以固定IP，这样访问套cf网站时，就不会重复安全验证了。
再多问一句，proxyip如何通过fofa扫描获得？个人如何搭建自己的proxyip？

**Comment by yonggekkk** [comment]
> > Proxyip与反代ip不相等！不能混用！Proxyip用默认的戓分享的就行
> 
> 感谢回复， 因为看了很多视频，把反代ip填在proxyip，可以固定IP，这样访问套cf网站时，就不会重复安全验证了。 再多问一句，proxyip如何通过fofa扫描获得？个人如何搭建自己的proxyip？

proxyip固定IP是片面的说法。proxyip主要作用是让你上CF类网站。
情况一，通常CF类网站或者支持CF的IP访问的网站：如果proxyip是一个IP，则检测proxyip为落地，就固定了这个IP。如果proxyip是个域名，里面包含各国的IP，那也会跳不同国家的IP。
情况二，有些网站不需要proxyip，落地IP是看你客户端的优选的IP地址为落地的：此时写不写proxyip无所谓，IP必在这个优选的IP的国家内跳，如果客户端的优选域名包含多个不同国家的IP，也会跳不同国家的IP

**Comment by yonggekkk** [comment]
> > Proxyip与反代ip不相等！不能混用！Proxyip用默认的戓分享的就行
> 
> 感谢回复， 因为看了很多视频，把反代ip填在proxyip，可以固定IP，这样访问套cf网站时，就不会重复安全验证了。 再多问一句，proxyip如何通过fofa扫描获得？个人如何搭建自己的proxyip？

至于你说的扫描proxyIP。。。我是没兴趣在这方面卷下去了，直接用其他大佬们扫的的吧。。

**Comment by yonggekkk** [comment]
> > > Proxyip与反代ip不相等！不能混用！Proxyip用默认的戓分享的就行
> > 
> > 
> > 感谢回复， 因为看了很多视频，把反代ip填在proxyip，可以固定IP，这样访问套cf网站时，就不会重复安全验证了。 再多问一句，proxyip如何通过fofa扫描获得？个人如何搭建自己的proxyip？
> 
> proxyip固定IP是片面的说法。proxyip主要作用是让你上CF类网站。 情况一，通常CF类网站或者支持CF的IP访问的网站，必填（托管在CF的网站或者类似chatgpt这类支持CF的IP访问的网站）检测proxyip为落地：如果proxyip是一个IP，就固定了这个IP。如果proxyip是个域名，里面包含各国的IP，那也会跳不同国家的IP。 情况二，大部分网站不需要proxyip，检测客户端的优选的IP地址为落地：此时写不写proxyip无所谓，IP必在这个优选的IP的国家内跳，如果客户端的优选域名包含多个不同国家的IP，也会跳不同国家的IP

**Comment by sylarrrm** [comment]
这个代码并不会实现 自选。你填什么地址 实际上还是worker去访问然后返回罢了 自选 只是让你访问worker可能容易点 但是worker用什么节点去访问 还是看运气
