### ISSUE TITLE
优选ip脚本无法使用

### ISSUE THREAD

**Issue by qaxc** [yonggekkk/Cloudflare-workers-pages-vless#51]
显示CANNOT LINK EXECUTABLE "curl": cannot locate symbol "SSL_get0_group_name" referenced by "/data/data/com.termux/files/usr/lib/libcurl.so"...

**Comment by yonggekkk** [comment]
去github下载termux

**Comment by qaxc** [comment]
> 去github下载termux
就是手机用termux用脚本后显示这个

**Comment by yonggekkk** [comment]
安装下curl。。还是这样就卸载Termux重装，或者在代理环境下安装

**Comment by qaxc** [comment]
感谢，重装后又可以了
