### ISSUE TITLE
ProxyIP

### ISSUE THREAD

**Issue by hosseinc** [yonggekkk/Cloudflare-workers-pages-vless#54]
hi
how to find new proxyIP?
could you please leave a germany proxyip?

**Comment by NiREvil** [comment]
it's all yours 
https://github.com/NiREvil/vless/blob/main/sub/ProxyIP.txt

**Comment by hosseinc** [comment]
Thanks a million

**Comment by hosseinc** [comment]
> it's all yours 
> 
> https://github.com/NiREvil/vless/blob/main/sub/ProxyIP.txt



Why did you deleted it? 😭

**Comment by NiREvil** [comment]
> Thanks a million

i dont, come here dude
https://t.me/F_NiREvil/5738
