### ISSUE TITLE
增加更多连接端口

### ISSUE THREAD

**Issue by redstoneleo** [yonggekkk/Cloudflare-workers-pages-vless#58]
建议增加更多连接端口，避免被轻松识别，
不知道这里的方法能不能用？https://foxhup.com/87

**Comment by yonggekkk** [comment]
看视频教程！cf vless本身默认就支持13个端口

**Comment by yonggekkk** [comment]
13个端口！你可以随便换

**Comment by redstoneleo** [comment]
问题是这类公开端口太具有辨识性了，探测到这些端口就知道多半是不老实的……

**Comment by yonggekkk** [comment]
> 问题是这类公开端口太具有辨识性了，探测到这些端口就知道多半是不老实的……

目前CF vless没被GFW针对过。。不急。。

**Comment by redstoneleo** [comment]
我这边用着用着流量一大（比如看视频）就会间歇性断流

**Comment by yonggekkk** [comment]
> 我这边用着用着流量一大（比如看视频）就会间歇性断流

正常！WS貌似是有这情况。本身WS协议被墙识别很容易。。
