### ISSUE TITLE
伪装网页不能使用了

### ISSUE THREAD

**Issue by cgan28** [yonggekkk/Cloudflare-workers-pages-vless#62]
现在的伪装网页，www.wto.org，好像有针对性地进行了封堵，导致节点不能使用了。前期的，央视海外网也不行。自定义，不知道该定义哪个？随便找了几个，也不行。

**Comment by yonggekkk** [comment]
没有这问题吧。不能用是什么意思

**Comment by yonggekkk** [comment]
你也可以把网页删除，不影响使用

**Comment by cgan28** [comment]
Redirects to www.wto.org are not allowed.


甬哥侃侃侃ygkkk ***@***.***> 于2024年3月14日周四 10:19写道：
