### ISSUE TITLE
求开源代码

### ISSUE THREAD

**Issue by sinspired** [yonggekkk/Cloudflare-workers-pages-vless#65]
研究了xui和badafans的代码，学习中，博主的开源代码可否提供学习一下？最近整梯子和go语言，这种有实用价值的代码太能激发学习积极性了。感谢！ggmomo@gmail.com

**Comment by yonggekkk** [comment]
workers本来就开源的
https://github.com/yonggekkk/Cloudflare-workers-pages-vless/blob/main/_worker.js

**Comment by honytao** [comment]
cloudflareST.exe这个，您应该是修改了xui的代码，想对照学习一下。
