### ISSUE TITLE
IP跳得太厉害了

### ISSUE THREAD

**Issue by AugustRothschild** [yonggekkk/Cloudflare-workers-pages-vless#66]
IP跳得太厉害了，一会儿在卢森堡、一会在美国。。。。。。请修改一下固定在美国呀，谢谢。

**Comment by yonggekkk** [comment]
关于这个，看说明https://youtube.com/shorts/e5GzA958e4A

**Comment by yonggekkk** [comment]
你这个应该是脚本自带的Proxyip域名在跳吧。。仅影响CF类网站。。你可以换下proxyIP

**Comment by AugustRothschild** [comment]
小白试试。我一直都是不时来看看，然后直接复制你的workers代码去重新布置，要是能自动复制你的代码然后自动布置到我的workers里就好了。

**Comment by yonggekkk** [comment]
> 小白试试。我一直都是不时来看看，然后直接复制你的workers代码去重新布置，要是能自动复制你的代码然后自动布置到我的workers里就好了。

这类CF vless脚本核心内容已经更新不出什么新东西来了。现在就优选IP与proxyip还能折腾。
