### ISSUE TITLE
增加LICENSE

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [yonggekkk/Cloudflare-workers-pages-vless#67]
这个repo并没有任何LICENSE。如果希望避免抄袭的话，可以增加一个比较多限制的LICENSE。

**Comment by yonggekkk** [comment]
当年某些人也有拿这个给我写文章的，在攻击面前，这些东西形同虚设。。。现在干脆不搞这些了。说明来源以及都不是我写的就是
