### ISSUE TITLE
chinese data stealers, use at your own risk 

### ISSUE THREAD

**Issue by NamasteIndia** [yonggekkk/Cloudflare-workers-pages-vless#68]
https://www.virustotal.com/gui/file-analysis/MjgxOGNiMGIyN2JiNzhlMWM1MDMxODcwMDA3NWE1NGI6MTcxMTY5MTAzNg==

![image](https://github.com/yonggekkk/Cloudflare-workers-pages-vless/assets/49607060/a423e599-bf40-49a9-a498-1ba4e0eff32e)

**Comment by yonggekkk** [comment]
显然，检测结果就是个笑话
此反代IP应用来源于这个作者https://github.com/badafans/Cloudflare-IP-SpeedTest
