### ISSUE TITLE
因为代码中的www.wto.org导致域名被封，太坑了

### ISSUE THREAD

**Issue by ccsdfsdzxces** [yonggekkk/Cloudflare-workers-pages-vless#71]
代码中的www.wto.org，被误认为滥用，域名没了，都不知道为啥别人的库里面都是国内域名，你这个为啥搞www.wto.org，很无语

**Comment by yonggekkk** [comment]
域名商太敏感了吧。你可以随便改呀，删除这个www.wto.org都没关系

**Comment by ccsdfsdzxces** [comment]
是啊，用的www.spaceship.com这个域名商，主要是还不给解封，说问题比较严重，等于域名没了，太坑，当时那边说www.wto.org我还一头雾水，居然还真找到了，不知道你为啥要加个 www.wto.org，我看其他类似的库都是国内网站啊

**Comment by yonggekkk** [comment]
不好意思哈，我删除了吧，反代公共网站在个别域名商看来的确有点问题

**Comment by ccsdfsdzxces** [comment]
Unfortunately, due to the nature of the abuse, it will not be possible to unsuspend or refund the service in question.


The decision is binding and final according to paragraph 7, “Acceptable Use Policy (AUP)” of our Universal TOS at https://www.spaceship.com/legal/universal-terms-of-service-agreement/#n-7-acceptable-use-policy-aupwhere it is stated that we have the sole right to decide what constitutes a violation and define the severity of corrective actions (a warning, suspension or immediate termination with no refund).

**Comment by yonggekkk** [comment]
> Unfortunately, due to the nature of the abuse, it will not be possible to unsuspend or refund the service in question.
> 
> The decision is binding and final according to paragraph 7, “Acceptable Use Policy (AUP)” of our Universal TOS at https://www.spaceship.com/legal/universal-terms-of-service-agreement/#n-7-acceptable-use-policy-aupwhere it is stated that we have the sole right to decide what constitutes a violation and define the severity of corrective actions (a warning, suspension or immediate termination with no refund).

感谢反馈
