### ISSUE TITLE
报522错误

### ISSUE THREAD

**Issue by hb5588973** [yonggekkk/Cloudflare-workers-pages-vless#73]
worker,昨天开始

**Comment by yonggekkk** [comment]
用pages部署吧。参考
https://youtu.be/PN0BLANXh4I
https://youtu.be/McdRoLZeTqg

**Comment by hb5588973** [comment]
Thanks!
The new deployments probably couldn't be used, including Pages. I had to roll back to make Pages work properly. That's how it is for now.

**Comment by yonggekkk** [comment]
项目说明已更新
