### ISSUE TITLE
刚刚只是更新了最新的workers代码，链接XXX.workers.dev报错。

### ISSUE THREAD

**Issue by jkwang** [yonggekkk/Cloudflare-workers-pages-vless#74]
Error 1101 
Worker threw exception

**Comment by jkwang** [comment]
用触发器设置的私有域名访问报Connection timed out Error code 522

**Comment by yonggekkk** [comment]
先用pages部署吧。参考
https://youtu.be/PN0BLANXh4I
https://youtu.be/McdRoLZeTqg

**Comment by Rehcah** [comment]
> Error 1101 Worker threw exception
一样报错，好几个都是这样 了

**Comment by xmu-hph** [comment]
彻底用不了了吧

**Comment by yonggekkk** [comment]
项目说明已更新
