### ISSUE TITLE
1101错误访问不到

### ISSUE THREAD

**Issue by aousx** [yonggekkk/Cloudflare-workers-pages-vless#75]
![image](https://github.com/yonggekkk/Cloudflare-workers-pages-vless/assets/37695244/d8f85987-5536-4566-a8ed-3884296833bd)

**Comment by yonggekkk** [comment]
删除原来的workers域名！新建吧

**Comment by aousx** [comment]
> 删除原来的workers域名！新建吧

已解决，应该是第一次用了会报错的代码。删除重新就好了
