### ISSUE TITLE
一键自动脚本没了？

### ISSUE THREAD

**Issue by djgao234** [yonggekkk/Cloudflare-workers-pages-vless#76]
一键自动脚本去哪儿了，难道不在这个库嘛😭

**Comment by yonggekkk** [comment]
你具体指哪个？

**Comment by djgao234** [comment]
就是自动选 IP 并进行测速，然后选出最快的 IP，自动把最优 IP 挂在 cloudflare 上的，我记得以前有个手动端还有个自动端的，现在怎么都没有了

**Comment by yonggekkk** [comment]
你是说warp吗？https://github.com/yonggekkk/warp-yg

**Comment by djgao234** [comment]
找到了，感谢🙏👍
