### ISSUE TITLE
能否支持直接添加订阅链接？

### ISSUE THREAD

**Issue by WDJSQZH** [yonggekkk/Cloudflare-workers-pages-vless#79]

**Comment by yonggekkk** [comment]
订阅链接要配合自动优选ip才有意义，不然没必要呀！

**Comment by WDJSQZH** [comment]
我是想把在vps上自建的节点加上去，所以有的这个想法



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年04月26日 10:40 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [yonggekkk/Cloudflare-workers-pages-vless] 能否支持直接添加订阅链接？ (Issue #79) |

订阅链接要配合自动优选ip才有意义，不然没必要呀！
