### ISSUE TITLE
新代码导致手机端异常的问题

### ISSUE THREAD

**Issue by EdenMoxe** [yonggekkk/Cloudflare-workers-pages-vless#80]
首先感谢甬哥和一众大佬提供那么好的开源项目！但是新版修改的代码似乎存在手机V2RayN（版本号1.7.6）无法正常使用的问题（能连接成功、能测延迟，但是浏览器无法访问外网），而电脑端的使用是一切正常的，旧版同样的节点配置方式则不存在这个问题，我看见频道上有人也遇到这个问题，是版本的原因还是代码原因呢？

**Comment by yonggekkk** [comment]
客户端更新到最新吧

**Comment by EdenMoxe** [comment]
浅浅研究一下：确实如甬哥所说，旧代码报1103错误是因为返回打印uuid函数引起的，删除了该返回函数，旧代码就能用了，而且电脑手机都能用节点，坏处就是不能看具体的vless信息了。

**Comment by Y3y1ng** [comment]
同样的问题，我已经回滚到第一版了
